version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  backend:
    build: ../backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sunny
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ../frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  blockchain-core:
    build: ../blockchain-core
    ports:
      - "26657:26657"  # Tendermint RPC
    volumes:
      - ./genesis.json:/app/genesis.json

volumes:
  mongo_data:
